apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends-app
  namespace: {{ .Values.namespace.name }}
  name: techtrends
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: techtrends-app
  type: {{ .Values.service.type }}
