apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends-app
  namespace: sandbox
  name: techtrends
spec:
  ports:
  - port: 4111
    protocol: TCP
    targetPort: 4111
  selector:
    app: techtrends-app
  type: ClusterIP
